default_stages: [commit]
default_language_version:
  # default language version for each language
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md,markdown"]
        stages: [commit]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: detect-aws-credentials
      - id: fix-encoding-pragma
      - id: detect-private-key
      - id: name-tests-test
        args: ["--django"]
      - id: end-of-file-fixer
        exclude: ^static/
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ^static/
        language: python
        types: [python]
        args: ["--line-length=120"]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
